Added arch detection to configure

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -9,6 +9,10 @@ cmd_exists() {
 	type "$1" > /dev/null && CC="$1";
 }
 
+failure() {
+	printf "FAILED: $1" && exit 1;
+}
+
 # Checking for C compiler
 cmd_exists clang
 cmd_exists cc
@@ -22,5 +26,20 @@ else
 	printf "No\n"
 fi
 
-# Check our arch
 
+# Check our arch
+case "$(arch)" in
+		arm*) ARCH=arm;;
+		*x32*) ARCH=x32;;
+		x86_64*) ARCH=x86_64;;
+		*) failure "Unknown architecture \"$0\""
+esac
+
+
+
+
+# Finally, emit our config
+cat <<EOF > config.mak
+ARCH=$ARCH
+CC=$CC
+EOF
